/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminNavbar: typeof import('./src/components/backoffice/dashboard/AdminNavbar.vue')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    CardClientesPorCobrar: typeof import('./src/components/backoffice/dashboard/panel/CardClientesPorCobrar.vue')['default']
    CardEstadoTareas: typeof import('./src/components/backoffice/dashboard/panel/CardEstadoTareas.vue')['default']
    CardOportunidesCreadas: typeof import('./src/components/backoffice/dashboard/panel/CardOportunidesCreadas.vue')['default']
    CardPagosPorQuincena: typeof import('./src/components/backoffice/dashboard/panel/CardPagosPorQuincena.vue')['default']
    CardPagosRecibidos: typeof import('./src/components/backoffice/dashboard/panel/CardPagosRecibidos.vue')['default']
    CardSeguimientos: typeof import('./src/components/backoffice/dashboard/panel/CardSeguimientos.vue')['default']
    CategoriaForm: typeof import('./src/components/backoffice/categoria/CategoriaForm.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTableCategoria: typeof import('./src/components/backoffice/categoria/DataTableCategoria.vue')['default']
    DataTableEmpresa: typeof import('./src/components/backoffice/empresa/DataTableEmpresa.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Editor: typeof import('primevue/editor')['default']
    EmpresaForm: typeof import('./src/components/backoffice/empresa/EmpresaForm.vue')['default']
    HeaderPage: typeof import('./src/components/shared/backend/HeaderPage.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputGlobalSearchContacto: typeof import('./src/components/backoffice/dashboard/InputGlobalSearchContacto.vue')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Panel: typeof import('primevue/panel')['default']
    PrimeDatatables: typeof import('./src/components/shared/PrimeDatatables.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderNotificaciones: typeof import('./src/components/backoffice/dashboard/SliderNotificaciones.vue')['default']
    SliderTareas: typeof import('./src/components/backoffice/dashboard/SliderTareas.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UserNavBar: typeof import('./src/components/backoffice/dashboard/UserNavBar.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
